flowchart TD
classDef Literal fill:#ffffff,stroke:#000000,color:;
classDef Literal_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E1_CRM_Entity fill:#ffffff,stroke:#000000,color:;
classDef crm_E1_CRM_Entity_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E2_Temporal_Entity fill:#82c3ec,stroke:#000000,color:;
classDef crm_E2_Temporal_Entity_URI fill:#d2e9f9,stroke:#000000,color:;
classDef crm_E55_Type fill:#fab565,stroke:#000000,color:;
classDef crm_E55_Type_URI fill:#fde7ce,stroke:#000000,color:;
classDef crm_E52_Time-Span fill:#86bcc8,stroke:#000000,color:;
classDef crm_E52_Time-Span_URI fill:#dcebef,stroke:#000000,color:;
classDef crm_E41_Appellation fill:#fef3ba,stroke:#000000,color:;
classDef crm_E41_Appellation_URI fill:#fffae6,stroke:#000000,color:;
classDef crm_E53_Place fill:#94cc7d,stroke:#000000,color:;
classDef crm_E53_Place_URI fill:#e1f1da,stroke:#000000,color:;
classDef crm_E77_Persistent_Item fill:#ffffff,stroke:#000000,color:;
classDef crm_E77_Persistent_Item_URI fill:#ffffff,stroke:#000000,color:;
classDef crm_E28_Conceptual_Object fill:#fddc34,stroke:#000000,color:;
classDef crm_E28_Conceptual_Object_URI fill:#fef6cd,stroke:#000000,color:;
classDef crm_E18_Physical_Thing fill:#e1ba9c,stroke:#000000,color:;
classDef crm_E18_Physical_Thing_URI fill:#f3e5d8,stroke:#000000,color:;
classDef crm_E39_Actor fill:#ffbdca,stroke:#000000,color:;
classDef crm_E39_Actor_URI fill:#ffe6eb,stroke:#000000,color:;
classDef crmpc_PC0_Typed_CRM_Property fill:#cc80ff,stroke:#000000,color:;
classDef crmpc_PC0_Typed_CRM_Property_URI fill:#ebccff,stroke:#000000,color:;
classDef Multi fill:#cccccc,stroke:#000000,color:;
classDef Multi_URI fill:#cccccc,stroke:#000000,color:;
2["crm:E67_Birth"]:::crm_E2_Temporal_Entity -->|crm:P96_by_mother| 3["crm:E21_Person"]:::crm_E39_Actor
subgraph 8 ["xsd:string"]
8a[<strong>Mother Appellation</strong>]:::Literal
click 8a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#mother-appellation" _blank
end
6["crm:E41_Appellation<br>crm:E33_Linguistic_Object"]:::Multi -->|crm:P190_has_symbolic_content| 8:::Literal
subgraph 10 ["xsd:dateTime"]
10a[<strong>Birth Date Begin</strong>]:::Literal
click 10a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birth-date-begin" _blank
end
9["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82a_begin_of_the_begin| 10:::Literal
2["crm:E67_Birth"]:::crm_E2_Temporal_Entity -->|crm:P4_has_time-span| 9["crm:E52_Time-Span"]:::crm_E52_Time-Span
subgraph 16 ["xsd:dateTime"]
16a[<strong>Death Date Begin</strong>]:::Literal
click 16a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#death-date-begin" _blank
end
15["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82a_begin_of_the_begin| 16:::Literal
subgraph 4 ["crm:E53_Place"]
4a[<strong>Birth Place</strong>]:::crm_E53_Place
click 4a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birth-place" _blank
4b["geoname:6050610<br><em>''Laval, Québec''@fr</em><br><em>''Laval, Quebec''@en</em>"]:::crm_E53_Place
click 4b "http://www.geonames.org/6050610" _blank
4a---4b
end
2["crm:E67_Birth"]:::crm_E2_Temporal_Entity -->|crm:P7_took_place_at| 4:::crm_E53_Place
subgraph 18 ["xsd:string"]
18a[<strong>Father Appellation</strong>]:::Literal
click 18a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#father-appellation" _blank
end
17["crm:E33_Linguistic_Object<br>crm:E41_Appellation"]:::Multi -->|crm:P190_has_symbolic_content| 18:::Literal
subgraph 19 ["xsd:dateTime"]
19a[<strong>Birth Date End</strong>]:::Literal
click 19a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birth-date-end" _blank
end
9["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82b_end_of_the_end| 19:::Literal
subgraph 20 ["xsd:dateTime"]
20a[<strong>Death Date End</strong>]:::Literal
click 20a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#death-date-end" _blank
end
15["crm:E52_Time-Span"]:::crm_E52_Time-Span -->|crm:P82b_end_of_the_end| 20:::Literal
13["crm:E69_Death"]:::crm_E2_Temporal_Entity -->|crm:P4_has_time-span| 15["crm:E52_Time-Span"]:::crm_E52_Time-Span
23["crm:E21_Person"]:::crm_E39_Actor -->|crm:P100i_died_in| 13["crm:E69_Death"]:::crm_E2_Temporal_Entity
subgraph 0 ["crm:E53_Place"]
0a[<strong>Death Place</strong>]:::crm_E53_Place
click 0a "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birth-place" _blank
end
13["crm:E69_Death"]:::crm_E2_Temporal_Entity -->|crm:P7_took_place_at| 0:::crm_E53_Place
11["crm:E21_Person"]:::crm_E39_Actor -->|crm:P1_is_identified_by| 17["crm:E33_Linguistic_Object<br>crm:E41_Appellation"]:::Multi
23["crm:E21_Person"]:::crm_E39_Actor -->|crm:P98i_was_born| 2["crm:E67_Birth"]:::crm_E2_Temporal_Entity
2["crm:E67_Birth"]:::crm_E2_Temporal_Entity -->|crm:P97_from_father| 11["crm:E21_Person"]:::crm_E39_Actor
3["crm:E21_Person"]:::crm_E39_Actor -->|crm:P1_is_identified_by| 6["crm:E41_Appellation<br>crm:E33_Linguistic_Object"]:::Multi
