graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#00C9E6, stroke:#000000;
classDef Type fill:#E18312, stroke:#000000;
classDef Time-Span fill:#2C9C91, stroke:#000000;
classDef Appellation fill:#FFEB7F, stroke:#000000;
classDef Place fill:#008836, stroke:#000000;
classDef Persistent_Item fill:#B266B2, stroke:#000000;
classDef Conceptual_Object fill:#FFD700, stroke:#000000;
classDef Physical_Thing fill:#D2B48C, stroke:#000000;
classDef Actor fill:#f58aad, stroke:#000000;
classDef PC_Classes fill:#4ce600, stroke:#000000;

0["crm:E21_Person"]:::Actor -->|crm:P98i_was_born| 2["crm:E67_Birth"]:::Temporal_Entity
0["crm:E21_Person"]:::Actor -->|crm:P100i_died_in| 4["crm:E69_Death"]:::Temporal_Entity
2["crm:E67_Birth"]:::Temporal_Entity -->|crm:P4_has_time-span| 5["crm:E52_Time-Span"]:::Time-Span
2["crm:E67_Birth"]:::Temporal_Entity -->|crm:P96_by_mother| 6["crm:E21_Person"]:::Actor
2["crm:E67_Birth"]:::Temporal_Entity -->|crm:P7_took_place_at| 7["crm:E53_Place"]:::Place
2["crm:E67_Birth"]:::Temporal_Entity -->|crm:P97_from_father| 9["crm:E21_Person"]:::Actor
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P4_has_time-span| 11["crm:E52_Time-Span"]:::Time-Span
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P7_took_place_at| 12["crm:E53_Place"]:::Place
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P120_occurs_before| 13["crm:E9_Move"]:::Temporal_Entity
5["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 14[xsd:dateTime]:::Literal
5["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 16[xsd:dateTime]:::Literal
11["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 23[xsd:dateTime]:::Literal
11["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 24[xsd:dateTime]:::Literal
13["crm:E9_Move"]:::Temporal_Entity -->|crm:P27_moved_from| 12["crm:E53_Place"]:::Place
13["crm:E9_Move"]:::Temporal_Entity -->|crm:P25_moved| 0["crm:E21_Person"]:::Actor
13["crm:E9_Move"]:::Temporal_Entity -->|crm:P26_moved_to| 31["crm:E53_Place"]:::Place
