graph TD
classDef Literal fill:#f2f2f2,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef CRM_Entity_URI fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#82C3EC, stroke:#000000;
classDef Temporal_Entity_URI fill:#d2e9f9,stroke:#000000;
classDef Type fill:#FAB565, stroke:#000000;
classDef Type_URI fill:#fde7ce,stroke:#000000;
classDef Time-Span fill:#86BCC8, stroke:#000000;
classDef Time-Span_URI fill:#dcebef,stroke:#000000;
classDef Appellation fill:#FEF3BA, stroke:#000000;
classDef Appellation_URI fill:#fffae6,stroke:#000000;
classDef Place fill:#94CC7D, stroke:#000000;
classDef Place_URI fill:#e1f1da,stroke:#000000;
classDef Persistent_Item fill:#FFFFFF, stroke:#000000;
classDef Persistent_Item_URI fill:#FFFFFF,stroke:#000000;
classDef Conceptual_Object fill:#FDDC34, stroke:#000000;
classDef Conceptual_Object_URI fill:#fef6cd,stroke:#000000;
classDef Physical_Thing fill:#E1BA9C, stroke:#000000;
classDef Physical_Thing_URI fill:#f3e5d8,stroke:#000000;
classDef Actor fill:#ffbdca, stroke:#000000;
classDef Actor_URI fill:#ffe6eb,stroke:#000000;
classDef PC_Classes fill:#FFFFFF, stroke:#000000;
classDef PC_Classes_URI fill:#FFFFFF,stroke:#000000;
classDef Multi_URI fill:#cccccc,stroke:#000000;

