graph TD
classDef Literal fill:#FFFFFF,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#82C3EC, stroke:#000000;
classDef Type fill:#FAB565, stroke:#000000;
classDef Time-Span fill:#86BCC8, stroke:#000000;
classDef Appellation fill:#FEF3BA, stroke:#000000;
classDef Place fill:#94CC7D, stroke:#000000;
classDef Persistent_Item fill:#FFFFFF, stroke:#000000;
classDef Conceptual_Object fill:#FDDC34, stroke:#000000;
classDef Physical_Thing fill:#E1BA9C, stroke:#000000;
classDef Actor fill:#ffbdca, stroke:#000000;
classDef PC_Classes fill:#FFFFFF, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;





